# Setup
title:               Thyreon
tagline:             'The Shield of Faith'
description:         'Defending the Christian faith'
url:                 https://thyreon.com
baseurl:             ''
paginate:            5
permalink:           /:title

# About/contact
author:
  name:              Nicodemus Gurion
  url:               https://thyreon.com
  email:             nicodemusbg@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown

